export const CartSelectorsArray = [
    'inventory-item-name',
    'inventory-item-desc',
    'payment-info-label',
    'payment-info-value',
    'shipping-info-label',
    'shipping-info-value',
    'subtotal-label',
    'tax-label',
    'total-label',
];

export const Selectors = {
    InventoryItemName: 'inventory-item-name',
    InventoryItemDesc: 'inventory-item-desc',
    InventoryItemPrice: 'inventory-item-price',
    PaymentInfoLabel: 'payment-info-label',
    PaymentInfoValue: 'payment-info-value',
    ShippingInfoLabel: 'shipping-info-label',
    ShippingInfoValue: 'shipping-info-value',
    SubtotalLabel: 'subtotal-label',
    TaxLabel: 'tax-label',
    TotalLabel: 'total-label',
    ItemQuantity: 'item-quantity',
    TextHeader: 'complete-header',
    TextComplete: 'complete-text',
    SocialTwitter: 'social-twitter',
    SocialFacebook: 'social-facebook',
    SocialLinkedin: 'social-linkedin',
    FooterCopyText: 'footer-copy',
    ShoppingCartLink: 'shopping-cart-link',
    AddToCartItem: 'add-to-cart-sauce-labs-backpack',
    AddToCartApprove: 'add-to-cart',
    AboutSidebar: 'about-sidebar-link',
    Title: 'title',
} as const;