name: Auto Create PR to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if PR exists
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_COUNT=$(gh pr list --base main --head dev --json number --jq 'length')
          echo "pr_count=$PR_COUNT" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_pr.outputs.pr_count == '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "🚀 Merge dev into main" \
            --body "## Автоматический Pull Request

          Этот PR был создан автоматически при пуше в ветку \`dev\`.

          ### Изменения
          - Просмотрите commits ниже
          - Проверьте код перед мерджем

          ---
          _Создано автоматически с помощью GitHub Actions_"

