name: Auto Create PR to Main

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "dev"
          destination_branch: "main"
          pr_title: "🚀 Merge dev into main"
          pr_body: |
            ## Автоматический Pull Request
            
            Этот PR был создан автоматически при пуше в ветку `dev`.
            
            ### Изменения
            - Просмотрите commits ниже
            - Проверьте код перед мерджем
            
            ---
            _Создано автоматически с помощью GitHub Actions_
          pr_allow_empty: false

